mysite/urls.py
# <<mysite.urls>>------------------------

from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('polls/', include('polls.urls')),

]

polls/urls.py
# <<polls.urls>>------------------
from django.urls import path
from polls import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/results/', views.results, name='results'),


]

polls/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question,
                                 on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text

polls/views.py
# <<polls.views>>------------------------
from django.shortcuts import render, get_object_or_404
from polls.models import Question
from django.http import HttpResponseRedirect
from django.urls import reverse

def index(request):
    question_list = Question.objects.all().order_by('-pub_date')
    context = {'my_list' : question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'my_question': question}
    return render(request, 'polls/detail.html', context)

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    selected_choice = question.choice_set.get(pk=request.POST['choice'])
    selected_choice.votes +=1
    selected_choice.save()

    return HttpResponseRedirect(reverse('polls:results',
                                        args=(question.id,)))

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'my_question': question}
    return render(request, 'polls/results.html', context)

def bulletin(request):
    bulletin_list = Bulletin.objects.all().order_by('-b_date')
    context = {'bulletin_context' : bulletin_list}
    return render(request, 'polls/../bulletin/templates/bulletin/bulletin.html', context)

polls/templates/polls/detail.html
<!--polls.templates.polls.detail>>-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/footers/">



    <!-- Bootstrap core CSS -->
<link href="/docs/5.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="footers.css" rel="stylesheet">
  </head>
  <body>

  <!--========헤드라인==========-->
    <div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-0 my-0 border-top">
    <p class="col-md-1 mb- text-muted">  </p>

  </footer>
</div>

    <center><a href="http://localhost:8000/">
      <img src="https://mblogthumb-phinf.pstatic.net/MjAyMDAxMDlfMTEx/MDAxNTc4NTU4OTEzNjI5.ypR-PGIv_jG_x1gwcgplGgdoxJC86q_NCHPonoGMukgg.o1uZ5c2iitGOGVczyseS1ljirJEstD9jFLJ8wMWpUIEg.JPEG.fw4gd/21608rQVLuL.jpg?type=w2" width="10%" >
      </a></center>
<br>

    <title>polls...</title>
    <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>


<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-0 my-0 border-top">
    <p class="col-md-1 mb- text-muted">  </p>

    <a href="/" class="col-md-1 d-flex align-items-center justify-content-center mb-0 mb-md-0 me-md-auto link-dark text-decoration-none">
      <svg class="bi me-1" width="0" height="1"><use xlink:href="#bootstrap"/></svg>
    </a>
  </footer>
</div>


    </ul>
  </footer>
</div>


<div class="b-example-divider" ></div>

<div class="container">
  <footer class="py-0 my-0">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="/" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="/bulletin/" class="nav-link px-2 text-muted">게시판</a></li>
      <li class="nav-item"><a href="/polls/" class="nav-link px-2 text-muted">투표</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
<!--============헤드라인 종료=============--><h1>
      <center>
{{ my_question.question_text }} </h1>

<form action="{% url 'polls:vote' my_question.id %}" method="post">

{% csrf_token %}
<center><br><br>
{% for tmp in my_question.choice_set.all %}
    <input type = "radio" name ="choice" id="choice{{ forloop.counter }}"
           value="{{ tmp.id }}">
     <label for="choice{{ forloop.counter }}">
    {{ tmp.choice_text }}</label><br>

{% endfor %}
<br><br>
    <input type="submit" value="제출">
</center>
</form>
  </center>
</body></html>

polls/templates/polls/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Welcome Zenna World</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/footers/">



    <!-- Bootstrap core CSS -->
<link href="/docs/5.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="footers.css" rel="stylesheet">
  </head>
  <body>

  <!--========헤드라인==========-->
    <div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-0 my-0 border-top">
    <p class="col-md-1 mb- text-muted">  </p>

  </footer>
</div>

    <center><a href="http://localhost:8000/">
      <img src="https://mblogthumb-phinf.pstatic.net/MjAyMDAxMDlfMTEx/MDAxNTc4NTU4OTEzNjI5.ypR-PGIv_jG_x1gwcgplGgdoxJC86q_NCHPonoGMukgg.o1uZ5c2iitGOGVczyseS1ljirJEstD9jFLJ8wMWpUIEg.JPEG.fw4gd/21608rQVLuL.jpg?type=w2" width="10%" >
      </a></center>
<br>

    <title>zennatheworld</title>
    <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>


<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-0 my-0 border-top">
    <p class="col-md-1 mb- text-muted">  </p>

    <a href="/" class="col-md-1 d-flex align-items-center justify-content-center mb-0 mb-md-0 me-md-auto link-dark text-decoration-none">
      <svg class="bi me-1" width="0" height="1"><use xlink:href="#bootstrap"/></svg>
    </a>
  </footer>
</div>


    </ul>
  </footer>
</div>


<div class="b-example-divider"></div>

<div class="container">
  <footer class="py-0 my-0">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="/" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="/bulletin/" class="nav-link px-2 text-muted">게시판</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">투표</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul> 수정
<!--============헤드라인 종료=============-->
   <div class="col">
 <center>
      <h1>질문을 먼저 고르세요를레이히</h1><br>

      <ul class="nav flex-column">
          {% for tmp in my_list %}
            <li class="nav-item mb-2"><a href="/polls/{{ tmp.id }}" class="nav-link p-0 text-muted">
            {{ tmp.question_text }}</a></li>
        {% endfor %}
      </ul>
    </div>

</center>
  <!--==============아래 로고================-->


    <br><br><br><br><br><br>
    <div class="container">

  <footer class="d-flex flex-wrap justify-content-between align-items-center py-50 my-50 border-top">
    <p class="col-md-1 mb- text-muted">  </p>

    <a href="/" class="col-md-1 d-flex align-items-center justify-content-center mb-20 mb-md-10 me-md-auto link-dark text-decoration-none">
      <svg class="bi me-1" width="0" height="0"><use xlink:href="#bootstrap"/></svg>
    </a>
  </footer>
</div>
<div class="b-example-divider"></div>
    <p class="text-center text-muted">&copy; ZennaWorld </p>
  </footer>
</div>

      
  </body>
</html>

polls/templates/polls/results.html
<!--polls.templates.polls.results>>-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/footers/">



    <!-- Bootstrap core CSS -->
<link href="/docs/5.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="footers.css" rel="stylesheet">
  </head>
  <body>

  <!--========헤드라인==========-->
    <div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-0 my-0 border-top">
    <p class="col-md-1 mb- text-muted">  </p>

  </footer>
</div>

    <center><a href="http://localhost:8000/">
      <img src="https://mblogthumb-phinf.pstatic.net/MjAyMDAxMDlfMTEx/MDAxNTc4NTU4OTEzNjI5.ypR-PGIv_jG_x1gwcgplGgdoxJC86q_NCHPonoGMukgg.o1uZ5c2iitGOGVczyseS1ljirJEstD9jFLJ8wMWpUIEg.JPEG.fw4gd/21608rQVLuL.jpg?type=w2" width="10%" >
      </a></center>
<br>

    <title>zennatheworld</title>
    <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>


<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-0 my-0 border-top">
    <p class="col-md-1 mb- text-muted">  </p>

    <a href="/" class="col-md-1 d-flex align-items-center justify-content-center mb-0 mb-md-0 me-md-auto link-dark text-decoration-none">
      <svg class="bi me-1" width="0" height="1"><use xlink:href="#bootstrap"/></svg>
    </a>
  </footer>
</div>


    </ul>
  </footer>
</div>


<div class="b-example-divider" ></div>

<div class="container">
  <footer class="py-0 my-0">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="/" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="/bulletin/" class="nav-link px-2 text-muted">게시판</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
<center>
<h1>check the results </h1><br>
고친게 깃에 들어가는지가 궁금한데

{% for tmp in my_question.choice_set.all %}
{#    #현재 질문에 대한 항목 전부 다 들고와라#}
    {{ tmp.choice_text }} - {{ tmp.votes }} 표 <br><br>
{#    #"사람이름 - 0표"출력#}
{% endfor %}

</center>
</body>
</html>

templates/home.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Zenna Universe</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/footers/">



    <!-- Bootstrap core CSS -->
<link href="/docs/5.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="footers.css" rel="stylesheet">
  </head>
  <body>

  <!--========헤드라인==========-->
    <div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-0 my-0 border-top">
    <p class="col-md-1 mb- text-muted">  </p>

  </footer>
</div>

    <center><a href="http://localhost:8000/">
      <img src="https://mblogthumb-phinf.pstatic.net/MjAyMDAxMDlfMTEx/MDAxNTc4NTU4OTEzNjI5.ypR-PGIv_jG_x1gwcgplGgdoxJC86q_NCHPonoGMukgg.o1uZ5c2iitGOGVczyseS1ljirJEstD9jFLJ8wMWpUIEg.JPEG.fw4gd/21608rQVLuL.jpg?type=w2" width="10%" >
      </a></center>
<br>

    <title>zennatheworld</title>
    <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>


<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-0 my-0 border-top">
    <p class="col-md-1 mb- text-muted">  </p>

    <a href="/" class="col-md-1 d-flex align-items-center justify-content-center mb-0 mb-md-0 me-md-auto link-dark text-decoration-none">
      <svg class="bi me-1" width="0" height="1"><use xlink:href="#bootstrap"/></svg>
    </a>
  </footer>
</div>


    </ul>
  </footer>
</div>


<div class="b-example-divider" ></div>

<div class="container">
  <footer class="py-0 my-0">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="/" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="/bulletin/" class="nav-link px-2 text-muted">게시판</a></li>
      <li class="nav-item"><a href="/polls/" class="nav-link px-2 text-muted">투표</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
<!--============헤드라인 종료=============--><h1>

<!--======================로고===============-->

    <br><br><br><br><br><br>
    <div class="container">

  <footer class="d-flex flex-wrap justify-content-between align-items-center py-50 my-50 border-top">
    <p class="col-md-1 mb- text-muted">  </p>

    <a href="/" class="col-md-1 d-flex align-items-center justify-content-center mb-20 mb-md-10 me-md-auto link-dark text-decoration-none">
      <svg class="bi me-1" width="0" height="0"><use xlink:href="#bootstrap"/></svg>
    </a>
  </footer>
</div>
<div class="b-example-divider"></div>
    <p class="text-center text-muted">&copy; ZennaWorld </p>
  </footer>
</div>


  </body>
</html>